spring:
  h2:
    console:
      enabled: true
      path: /db
  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true

database:
  driverClassName: org.h2.Driver
  url: jdbc:h2:~/trabalhospring/DB_CLOSE_ON_EXIT=FALSE
  username: fiap
  password: fiap

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  show_sql: true
  format_sql: true
  hbm2ddl.auto: validate

file:
  input: classpath:lista_alunos1.txt