DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS AUTH;
DROP TABLE IF EXISTS PAGAMENTO;
DROP TABLE IF EXISTS CARTAO_CREDITO;
DROP SEQUENCE IF EXISTS PAGAMENTO_SEQUENCE;
DROP SEQUENCE IF EXISTS CARTAO_CREDITO_SEQUENCE;

CREATE TABLE USUARIOS(
  USERNAME VARCHAR_IGNORECASE(50) NOT NULL PRIMARY KEY,
  PASSWORD VARCHAR_IGNORECASE(200) NOT NULL,
  ENABLED BOOLEAN NOT NULL
);

CREATE TABLE AUTH(
  USERNAME VARCHAR_IGNORECASE(50) NOT NULL,
  AUTHORITY VARCHAR_IGNORECASE(50) NOT NULL,
  CONSTRAINT FK_AUTH_USUARIOS FOREIGN KEY(USERNAME) REFERENCES USUARIOS(USERNAME)
);

CREATE TABLE PAGAMENTO(
  ID_PAGAMENTO INTEGER NOT NULL,
  ID_PEDIDO INTEGER,
  STATUS INTEGER,
  ID_ESTUDANTE VARCHAR(8),
  TOTAL_PEDIDO DECIMAL (19,2),
  CREATION_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP,
  PRIMARY KEY (ID_PAGAMENTO)
);

CREATE TABLE CARTAO_CREDITO(
  ID INTEGER NOT NULL,
  NUMERO_CARTAO VARCHAR(16),
  CURSO VARCHAR(6),
  DATA_VALIDADE VARCHAR(5),
  NOME VARCHAR (200),
  REGISTRO VARCHAR(8),
  VERIFICADOR INTEGER,
  PRIMARY KEY(ID)
);

CREATE SEQUENCE PAGAMENTO_SEQUENCE START WITH 11 INCREMENT BY 1;

CREATE SEQUENCE CARTAO_CREDITO_SEQUENCE INCREMENT BY 1;